FROM node:22-alpine AS builder

RUN npm config set registry=https://mirrors.huaweicloud.com/repository/npm/

WORKDIR /app

COPY webUI/ .

RUN npm install && npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html